# Generated by Django 4.1 on 2022-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_combos_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
